name: Build & Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 19.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i
      - run: npm run build

  tests:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ env.DATABASE_URL }}
      JWT_ACCESS_TOKEN_SECRET: ${{ env.JWT_ACCESS_TOKEN_SECRET }}
      JWT_REFRESH_TOKEN_SECRET: ${{ env.JWT_REFRESH_TOKEN_SECRET }}

    strategy:
      matrix:
        node-version: [ 18.x, 19.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i
      - run: npm run test
      - run: npm run test:cov

      - name: Display custom environment variables
        run: |
          echo "DATABASE_URL::: ${{ env.DATABASE_URL }}"
          echo "JWT_ACCESS_TOKEN_SECRET::: ${{ env.JWT_ACCESS_TOKEN_SECRET }}"
          echo "JWT_REFRESH_TOKEN_SECRET::: ${{ env.JWT_REFRESH_TOKEN_SECRET }}"

